CREATE TABLE VOTES_REGISTRY
(
    ID          UUID PRIMARY KEY,
    ELECTION_ID UUID      NOT NULL,
    PUBLIC_KEY  TEXT      NOT NULL,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX VOTES_REGISTRY_UNIQUE_IDX ON VOTES_REGISTRY USING BTREE (ELECTION_ID, PUBLIC_KEY);