FROM node:13-alpine
RUN apk update && apk add --no-cache make gcc g++ python bash git findutils
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json

COPY tsconfig.json tsconfig.json
COPY tslint.json tslint.json
COPY src src
COPY versions.json versions.json
COPY .env .env
CMD npm run test-ci
